
export const VIEW_EARLIER_DASHBOARD = 'VIEW_EARLIER_DASHBOARD';
export const VIEW_LATER_DASHBOARD = 'VIEW_LATER_DASHBOARD';
export const ZOOM_IN = 'ZOOM_IN';
export const ZOOM_OUT = 'ZOOM_OUT';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const PROJECT_CREATED = 'PROJECT_CREATED';

export const REQUEST_PROJECT = 'REQUEST_PROJECT';
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';

export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';

export const FETCH_ERROR = 'FETCH_ERROR';