
export const VIEW_EARLIER_DASHBOARD = 'VIEW_EARLIER_DASHBOARD';
export const VIEW_LATER_DASHBOARD = 'VIEW_LATER_DASHBOARD';
export const ZOOM_IN = 'ZOOM_IN';
export const ZOOM_OUT = 'ZOOM_OUT';

export const CREATE_PROJECT_REQUESTED = 'CREATE_PROJECT_REQUESTED';
export const CREATE_PROJECT_SUCCEEDED = 'CREATE_PROJECT_SUCCEEDED';

export const DELETE_PROJECT_REQUESTED = 'DELETE_PROJECT_REQUESTED';
export const DELETE_PROJECT_SUCCEEDED = 'DELETE_PROJECT_SUCCEEDED';

export const PROJECTS_REQUESTED = 'PROJECTS_REQUESTED';
export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED';

export const PROJECT_ACTIVITIES_REQUESTED = 'PROJECT_ACTIVITIES_REQUESTED';
export const PROJECT_ACTIVITIES_RECEIVED = 'PROJECT_ACTIVITIES_RECEIVED';

export const UPDATE_PROJECT_REQUESTED = 'UPDATE_PROJECT_REQUESTED';
export const UPDATE_PROJECT_SUCCEEDED = 'UPDATE_PROJECT_SUCCEEDED';

export const ADD_PHASE_REQUESTED = 'ADD_PHASE_REQUESTED';
export const ADD_PHASE_SUCCEEDED = 'ADD_PHASE_SUCCEEDED';

export const UPDATE_PHASE_REQUESTED = 'UPDATE_PHASE_REQUESTED';
export const UPDATE_PHASE_SUCCEEDED = 'UPDATE_PHASE_SUCCEEDED';

export const REMOVE_PHASE_REQUESTED = 'REMOVE_PHASE_REQUESTED';
export const REMOVE_PHASE_SUCCEEDED = 'REMOVE_PHASE_SUCCEEDED';

export const EMPLOYEE_REQUESTED = 'EMPLOYEE_REQUESTED';
export const EMPLOYEE_RECEIVED = 'EMPLOYEE_RECEIVED';

export const FETCH_ERROR = 'FETCH_ERROR';
